name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio flake8
      - name: Check lock file
        run: |
          pip freeze | sort > requirements.lock.ci
          diff -u requirements.lock requirements.lock.ci
          rm requirements.lock.ci
      - name: Lint
        run: flake8 utils tests
      - name: Test
        run: pytest
